### ISSUE TITLE
Armament needs option to override offset for muzzle

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#105]
Currently `Armament` always calculates muzzle offset using `LocalOffset` as base. However (virtual) sprites for muzzle flashes are created from original sprites that have muzzle flash baked into turret sprite. Thus Armaments for units like ST 01B or MT200 can't change offset of the muzzle.

Changes to `Armament` in `OpenRA` are necessary: they're implemented in this PR: https://github.com/OpenRA/OpenRA/pull/20771

**Comment by Dzierzan** [comment]
Perhaps you should write trait something like `WithCustomMuzzleOverlay`? Basically render muzzle flash when primary armament shoots. So what `WithMuzzleOverlay` already does but without link to `LocalOffset`.
