### ISSUE TITLE
Virtual assets: per-frame offsets

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#128]
Allow changing offsets per each frame. YAML should look like this:

```
vehicle_raptor_ad: Player Shadow
    idle: 154,184,161,183,168,185,175,186,182 16
    move: 148-182[0:6:1] 8
    move.turn: 154,149,161,156,168,164,175,171,182,177 8
    shadow: 686-690 8
        offset: 6,5,0[0-2], 3,2,0[3-4], 1,1,0[5-6], 3,3,0[7]
```

`offset` field is a list of items with following syntax:

`<offset>[<frame_list>]`

where:
- `<frame_list>`: list of frame indices or range of frame indices
- `<offset>` is offset applied to frames specified in `<frame_list>`

Frame indices refer to indices in the parent sequence, e.g. `shadow` sequence has 8 frames and indices in `offset` field refer to these frames.

This is necessary for raptors' shadows (#17), infantry and probably also for other stuff.

**Comment by IceReaper** [comment]
Implemented!
You can now add "Offsets: ..." under each animation entry.
Format of the value is as follows:
`<frameSelector>:<x>,<y>`

FrameSelector can be like
`0` `0,2,3` `0,4-9,10`, .. Any combination of single frame numbers or ranges.
