### ISSUE TITLE
Miner (ED): reskin machine gun

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#130]
Create custom sprites for machine gun used by Miner (ED) by reskinning existing sprites to make colors better match ED colors.

@Dzierzan

**Comment by Dzierzan** [comment]
I require extracted muzzle flash sprites as I need to keep them as seperate sprites. I was considering baking them with main gun, but then it would break cloaking feature.

**Comment by Dzierzan** [comment]
![turret_miner_bt vspr-sheet](https://github.com/michaeldgg2/OpenE2140/assets/17529329/9fcc1b06-1a32-48d1-ab1e-9a9924b89259)

**Comment by michaeldgg2** [comment]
Implemented in https://github.com/OpenE2140/OpenE2140/commit/c848d18ccb57abe7de790d26f01064944dab5971 (#250).
