### ISSUE TITLE
Implement aircraft

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#156]
- [x] ED aircraft (@Dzierzan)
- [x] UCS aircraft (@Dzierzan)
   - [x] Gargoil
   - [x] Hell Wind
   - [x] Gargoil II
- [x] Heavy Lifter (basic unit)

**Comment by Dzierzan** [comment]
UCS aircrafts are added.

**Comment by Dzierzan** [comment]
Heavy Lifter added in 147f5ec7b7321078acb990f291492768803c54d5.
