### ISSUE TITLE
Incorrect hit shapes on some buildings

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#159]
Some buildings have incorrect hit shape.

![Screenshot_20230419_235134](https://user-images.githubusercontent.com/119738087/233208120-c8b2c48b-0774-423d-967b-18a4970b0277.png)

In this case it means that hitting the elevator door does not damage to Tech House at all:

![Screenshot_20230419_235352](https://user-images.githubusercontent.com/119738087/233208414-1a4c1bc3-7140-4c10-9ee7-6c739890bb03.png)

Buildings:
- [x] Tech House
- [x] Power Plant
![Screenshot_20230419_235436](https://user-images.githubusercontent.com/119738087/233208658-98fdea16-b2e6-4d2d-b8c1-e738b81775e2.png)
- [x] Construction Center
![Screenshot_20230419_235823](https://user-images.githubusercontent.com/119738087/233209103-bffd8ec8-83a8-4204-a3ef-74e1d946ad80.png)
- [x] Production Center
![Screenshot_20230419_235957](https://user-images.githubusercontent.com/119738087/233209398-7bff6b48-cb9e-4229-8663-fee89a15cfe4.png)

**Comment by Dzierzan** [comment]
Should elevators be targetable? I can do this task, but I wouldn't make the elevators targetable, just the main structures.

**Comment by Dzierzan** [comment]
Issue can be closed now.
