### ISSUE TITLE
Implement RAPTOR shadow rendering

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#17]
RAPTOR ES/AD sprites don't have shadow included, separate sprites are used to render shadow.

OpenE2140:
![Screenshot_20230203_173434](https://user-images.githubusercontent.com/119738087/216656712-b2925fc9-0626-4710-a599-ab432cc9dee7.png)

Earth 2140:
![Screenshot_20230203_173622](https://user-images.githubusercontent.com/119738087/216657093-51658b32-4d48-4299-b4ad-8ad7fafc19c9.png)

**Comment by Dzierzan** [comment]
Big Mech will require it as well.
