### ISSUE TITLE
Air Base sprites: fix transition between left helipad and main part of the building

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#170]
Transition from left helipad sprite to sprite for the main part is ugly:

![Left helipad](https://user-images.githubusercontent.com/119738087/234254933-31045d20-0488-405c-9fc5-b63b49fcc683.png)

Air Base is implemented correctly, the issue is in Earth 2140 too.

Just for reference, this is how the transition looks for the right helipad:

![Right helipad](https://user-images.githubusercontent.com/119738087/234255088-094dcd3f-9055-4a95-8f77-1048caf77db6.png)

**Comment by Dzierzan** [comment]
Fixed here 78cc909b378b1a45e54a2a7e295b74189de0fc89.
