### ISSUE TITLE
Custom warhead for spawning randomized shrapnel projectiles

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#174]
There are many instances where an explosion spawns flying debris in Earth 2140. These are:
- exploding building when it's dead.
- exploding vehicle when it's dead
- some missile's spawn debris when they explode (ST 02 or Tiger Assault)

An explosion is synced with spawning debris so that means a new warhead needs to be written in order to support that. Considering `CreateEffectWarhead` already supports `Delay` which is perfect for delayed exploding building, IMO it would serve as a base of a new warhead. Potential new warhead would have to do:

- use `CreateEffectWarhead` as base
- have `ShrapnelWeapon`  so basically what debris weapon it has to fire when an explosion is spawned
- `ShrapnelAmount` how many debris/particles `ShrapnelWeapon` has to spawn/fire.
- `Radius` ability to randomize X and Y offsets of explosions. It seems that explosions in Earth have fixed offsets. IMO that's not really a good approch and OpenE2140 would benefit from randomization.
- `LocalOffset` ability to shift the epicentrum of explosions. Center position of actors can be sometimes wacky and it would nice to be able to shift that. It would work nicely with `Radius`

Suffice to say, OpenE2140 needs a baby of `CreateEffectWarhead` and `ThrowsShrapnel` traits.

![Image](https://user-images.githubusercontent.com/17529329/234651213-aa72eb09-ee14-4fcc-a88d-a1a917824905.gif)

![Image](https://user-images.githubusercontent.com/17529329/234651647-bbb0db99-927f-4769-b627-96da54b93362.gif)

![Image](https://user-images.githubusercontent.com/17529329/234651993-857bda56-84a5-4a79-801a-0330a787604a.gif)

**Comment by michal-mad** [comment]
- [x] add shrapnel warhead
- [ ] add explosion extra support
