### ISSUE TITLE
Add Mine building

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#219]
Make sure that mining towers' rotation is updated less frequently than frequency at which the mine intermittently has power supply, when there's shortage of power.

![mine_low_power](https://github.com/OpenE2140/OpenE2140/assets/119738087/0b165866-2319-406a-a64b-6f10ebcca6f3)

**Comment by Dzierzan** [comment]
If you ask me, it's a super minor detail, not worth working on.

That's how it works in OpenE2140 and it is really good enough.
![mine](https://github.com/OpenE2140/OpenE2140/assets/17529329/35eb2f3c-00c2-4514-927d-b1e95dbc637f)

**Comment by michaeldgg2** [comment]
You're right, let's leave it for now.
