### ISSUE TITLE
Implement Teleport

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#226]
- [x] basic building
- [x] on production complete visual effect
- [x] on production complete sound effect
- [x] cost modifier for all produced units (custom `ProductionQueue`)
- [x] restrict units that can be produced

Not directly related, but still necessary:
- [x] #228

**Comment by michaeldgg2** [comment]
Being implemented in #209

**Comment by IceReaper** [comment]
Add modifier to tooltip so the costs are properly down

**Comment by michaeldgg2** [comment]
We can't use `ProductionCostMultiplier` to change cost, because that has to be applied to each unit and is global (it's use case is different from what we need). We need custom `ProductionQueue` to change the cost via the factory building.

**Comment by Dzierzan** [comment]
@michaeldgg2 that task is fully finished.
