### ISSUE TITLE
Infantry doesn't aim after shooting and moving.

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#235]
When you move infantry after they shot and target a new entity, aiming animation doesn't kick in. It kicks in properly after shooting.

![bug](https://github.com/OpenE2140/OpenE2140/assets/17529329/2e3c39f6-0996-470b-b39a-f1c19b281b48)

**Comment by michaeldgg2** [comment]
It's likely similar problem to #231
