### ISSUE TITLE
Indicator of building being powered down by the player

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#241]

**Comment by Dzierzan** [comment]
Not sure if it looks fine using cursor art.

![image](https://github.com/OpenE2140/OpenE2140/assets/17529329/431e67aa-6cb2-46bf-b7b1-47ce7bb76693)
![image](https://github.com/OpenE2140/OpenE2140/assets/17529329/c9732256-b57f-4775-9fae-69b0298f0315)

**Comment by michaeldgg2** [comment]
Implemented in 365c760
