### ISSUE TITLE
Support `LowSubtractive` blend mode

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#245]
![234651993-857bda56-84a5-4a79-801a-0330a787604a](https://github.com/OpenE2140/OpenE2140/assets/17529329/e4ac2a3b-f28f-4958-88b5-b15f0cbc2b72)

Required for smoke effect when a debris hits the ground. ORA does not have this mode. In the GIF you can clearly see it's `Subtractive` but it needs to be toned down, just like `LowAdditive` is.

**Comment by michaeldgg2** [comment]
After discussion we chose different approach (manually editing smoke sprites).
