### ISSUE TITLE
BIO unit

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#252]
- [x] basic unit: #248
- [x] #321

**Comment by Dzierzan** [comment]
The question is how. I mean original behavior is quite antient and requires a lot of micromanagment. Why not implement one of these two solutions:

- BIO "attacks" infantry which heal them
- BIO has healing aura which heals all infantry units around it.

Of course if you prefer original behavior, so be it.

**Comment by michaeldgg2** [comment]
We'll implement healing inside a small radius (likely 1.5 cell, so BIO doesn't become too powerful).

BIO can also replenish mines that Android A04 has used. We'll require that A04 enters BIO, so laying mines doesn't become too "cheap".
