### ISSUE TITLE
Improve custom shrapnel warhead. 

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#275]
In the original game you can notice that let's say 'debris1' particle is spawned, when it lands it keeps its correct sprite, which is still 'debris1'.

Right in OpenE2140 when debris particle hits the ground, random debris particle is spawned. Basically it is chosen from the explosion pool.

So proposed solution would be creating 6 weapons, each for invidual debris and create explosion warhead for each of them. That ensures that flying debris1 spawns debris1, debris2 spawns debris2 and so on.

@michal-mad would have to upgrade his warhead  trait so it could support multiple weapons BUT still spawn correct amount of particles. Right now if you set let's say two weapons, then amount of particles will be doubled.

**Comment by michaeldgg2** [comment]
We should implement better solution to avoid such ugly duplication. My solution (with prototype here: https://github.com/michaeldgg2/OpenE2140/commit/5a37d20009509370cd657cf032b1c94e405833ab) is based on `Bullet` as base weapon for the shrapnels. It however requires changes to `Bullet` to make it more customizable, the PR is almost complete: https://github.com/OpenRA/OpenRA/pull/20931
