### ISSUE TITLE
Miner (BT): minelaying animation

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#317]
New `WithDeployMineAnimation` trait, needs extensibility points in `LayMines` activity.

Light animation: red, white, red, white, red

**Comment by Dzierzan** [comment]
Needs to also work for disarming mines.

**Comment by michaeldgg2** [comment]
Implemented in d9bca931e0b6bcfe60cb84693e50f8ca916855e1 (and 46094e511f74793edbf383c8980cdd88b994b9eb)
