### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [OpenE2140/OpenE2140#336]
Hi,

I was wondering if you plan to support the [two](https://archive.org/details/earthusin) [demos](https://archive.org/details/Earth2140Demo), which could be useful for people to play some part of the game using this engine, without the need to buy it.

**Comment by michaeldgg2** [comment]
With regards to demo(s), we would really, really like to support it/them. However, they do not contain all the necessary content that we need (mainly assets related to new units/buildings in MP2, but also the new tileset), so it definitely can't be a drop-in replacement to the assets from the full game.

We will try to come back to this some time later and give it some more time to figure out, if and how to do this.

#339
