### ISSUE TITLE
Virtual assets: cannot define offsets independently for flipped and non-flipped frames

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#357]

**Comment by Dzierzan** [comment]
Examples, pay extra attention to the center. And in vanilla it's correct. It's a minor issue, but it doesn't mean it can be neglected.
![medium](https://github.com/OpenE2140/OpenE2140/assets/17529329/2911d3ae-ee70-4473-bc7f-76974b19e60e)
![small](https://github.com/OpenE2140/OpenE2140/assets/17529329/1538c1b9-6893-4d56-9bd8-777b59d27496)

It's needed for I believe all actors.

**Comment by IceReaper** [comment]
Implemented in latest commit.
