### ISSUE TITLE
Installer Not Detecting Install

### ISSUE THREAD

**Issue by ben132** [OpenE2140/OpenE2140#381]
I have just downloaded Earth 2140 HD on steam and the installer cannot detect the install.  I dont know wether it is because of it being the HD version, if so I don't think there is a way to download the original,

**Comment by IceReaper** [comment]
In which language did you install? It's likely the .exe checksum doesn't match

**Comment by ben132** [comment]
It should be the English version and it does say that it should be accepted as a valid install

**Comment by IceReaper** [comment]
https://steamdb.info/app/253860/depots/
There was no update lately.. but it lists a Mac version. Is this on Mac eventually?

**Comment by ben132** [comment]
I am on Windows, so it shouldnt have downloaded the Mac version.  Is there away to manually import the data?

**Comment by ben132** [comment]
I have figured out what has happened.  It was not able to Detect the install on a Drive other that C:   I have a D and G drive it could not find the install on the G drive.  I dont know wether is it an issue with the engine or OpenE2140s implementation.

**Comment by IceReaper** [comment]
Openra Steam detection checks steam path in registry. Then the manifest file in Steam Apps folder for the install location. Do you also have steam itself somewhere else? I'm interested in fixing that particular case tbh. Except if you for example hand-moved the steam folder. That would be undetectable

**Comment by ben132** [comment]
I havent got it intalled anywhere else but I have a steam.exe on the d drive, because of a mod.  But I havent opened started that exe for a while.

**Comment by IceReaper** [comment]
Did you install steam on d then from the beginning? Or did you simply move the steam folder by hand?

**Comment by ben132** [comment]
I installed steam on C then copied just the exe file, so steam could see a game there I dont know why it worked but I havent deleted since.  But I didnt move any other files from steam.

**Comment by IceReaper** [comment]
We can't support that at all. Games need logic to find (or search all drives, which can take hours). So every openra mod expects that steam resides on the location where the installer .exe installed steam. Inside steam you can then manage libraries. Even define another drive as library location. Openra supports all of that. But the manual move of stuff breaks any detection logic :(
