### ISSUE TITLE
Implement proper missile trail

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#40]
Replace currently used contrail generated by OpenRA with missile trail created from original game's sprites.

**Comment by michal-mad** [comment]
![screen3](https://user-images.githubusercontent.com/24232344/222502222-dfb714e4-238f-4885-b1d9-bcb16f194f68.jpg)

**Comment by michaeldgg2** [comment]
Implemented in 637e506 and 62490ca. Current version is deemed as acceptable:

![opene2140_missile_trail](https://user-images.githubusercontent.com/119738087/225065369-153c8919-c4a3-419b-9056-dfeeda9661cf.png)
