### ISSUE TITLE
Minelayers sometimes lays mine at incorrect location

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#406]
Affects both Miners and A04s. The bug appeared after updating engine with changes to `LayMines` activity.

![Image](https://user-images.githubusercontent.com/119738087/254073069-eb7a0e90-a358-4d20-8697-67f1fa1a4b95.gif)

It doesn't seem to affect Minelayer in RA mod.

**Comment by Dzierzan** [comment]
This might also related to it:

![a04](https://github.com/OpenE2140/OpenE2140/assets/17529329/cc06565d-860d-4030-a2be-c04cba246525)

**Comment by michaeldgg2** [comment]
Yes, it's the exact same bug, just the missing animation is very difficult to see on Miner.

This PR in OpenRA fixes it: https://github.com/OpenRA/OpenRA/pull/20968
