### ISSUE TITLE
Mines don't leave craters upon explosion

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#448]
Unfortunately adding `LeaveSmudges` warhead to `shared_misc_landmine` doesn't seem to work (even with 100% chance of leaving the smudge):

```
shared_misc_landmine:
	Warhead@SmudgeClear: LeaveSmudge
		SmudgeType: Clear
		Chance: 100
		ValidTargets: Ground
		InvalidTargets: Vehicle, Structure, Water
	Warhead@SmudgeSand: LeaveSmudge
		SmudgeType: Sand
		Chance: 100
		ValidTargets: Ground
		InvalidTargets: Vehicle, Structure, Water
	Warhead@Damage: SpreadDamage
		Spread: 256
		Damage: 50
		DamageTypes: Explosion
		ValidTargets: Ground, Vehicle, Infantry
		InvalidTargets: Mine
	Warhead@EffectGround: CreateEffect
		Image: explosion
		Explosions: projectile_explosion_1, projectile_explosion_2
		ExplosionPalette:
		ImpactSounds: 14.smp
		ValidTargets: Ground
	Warhead@EffectShrapnels: SpawnWeapons
		Weapons: weapon_debris_smoke
		Range: 1c0, 1c512
		Pieces: 2,2
		ValidTargets: Ground
```

**Comment by T-Zema** [comment]
You mean when selecting mine and autodestructing it? Maybe it can be fixed when destruction occures add also `Inherits: Smudges` 
I don't know where it is. I just was messing in `craters.yaml`
In DOS version i noticed it when you hit it with standard tank it explodes and always create a crater just like in example without mine

**Comment by michaeldgg2** [comment]
It doesn't matter. This is about what the mine does, when it is destroyed. Unfortunately inheriting from `Smudges` (or even increasing chance to 100%) doesn't work, neither does removing `InvalidTargets`. There must be an issue, but somewhere else.

**Comment by michaeldgg2** [comment]
OK, I got it, the `LeaveSmudges` trait was missing `AffectsParent: true`:

![opene2140_smudges_affectsparent](https://github.com/OpenE2140/OpenE2140/assets/119738087/8b6d6566-a8c9-40fe-93bc-4ad108839fcf)

**Comment by T-Zema** [comment]
Ok. Thank you. One step how C# works i think
