### ISSUE TITLE
[Crash] Cannot locate type: ModelWidget

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#508]
It happens after this commit 1ecc7e0c5977273469facf80470ef658c5436f26

[exception-2023-10-14T173351Z.log](https://github.com/OpenE2140/OpenE2140/files/12908102/exception-2023-10-14T173351Z.log)

**Comment by michaeldgg2** [comment]
This was properly fixed in OpenRA/OpenRA@36d4492. The hack in OpenE2140 was removed in 3486ae37ebfdf677f98db2d48a0247678f459cc4 with the engine update.
