### ISSUE TITLE
Offset of MCU deployment animation does not match with the MCU position

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#521]
Other buildings might be affected too.

![Image](https://github.com/OpenE2140/OpenE2140/assets/119738087/808eff50-68d5-4f29-a59f-094dc1e98042)

**Comment by Dzierzan** [comment]
Apparently `TransformSequence` is only missing for `Constr. Center`. Offsets for other buildings were already adjusted.
