### ISSUE TITLE
Exit cell is wrong for both barracks.

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#527]
Probably commit c9e9685fd95202eb0b2ccaa287abdc25daf7d180 broke that.

![barracks](https://github.com/OpenE2140/OpenE2140/assets/17529329/4fc2a5ef-826d-4405-bc92-dd62144a3287)

![barracks2](https://github.com/OpenE2140/OpenE2140/assets/17529329/5b4f6005-b8a0-4180-85ea-276b3b38ee03)

**Comment by michaeldgg2** [comment]
Actually the cause of this bug was due to change in engine (the bug appeared after updating engine in 1ecc7e0c5977273469facf80470ef658c5436f26).
