### ISSUE TITLE
HCU-M repair animation bug.

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#530]
If HCU-M actor is disabled by ion weapon during repairing another actor, the turrent animation is not stopped and it appears to be very buggy.

![hcum-bug](https://github.com/OpenE2140/OpenE2140/assets/17529329/c2c8ce37-8e7b-4a2f-b385-950f133ed88e)

![hcum-bug2](https://github.com/OpenE2140/OpenE2140/assets/17529329/4dd45985-6d10-4c0b-a29f-34486156d6a7)

![hcum-bug3](https://github.com/OpenE2140/OpenE2140/assets/17529329/cf6cefb6-0d6c-4153-b62a-ed68b40f01dd)

**Comment by michaeldgg2** [comment]
Duplicate of #495
