### ISSUE TITLE
Mechs should use `move` animation when they turn.

### ISSUE THREAD

**Issue by Dzierzan** [OpenE2140/OpenE2140#67]
In Earth 2140 actors (probably only mech) use moving animation for turning. However it's not full movement either. I suppose they made it like that to mimic mini steps.

![rotate](https://user-images.githubusercontent.com/17529329/224128054-7524386b-1af0-45c0-9135-8c4b37c3c5ec.gif)
![rotate2](https://user-images.githubusercontent.com/17529329/224128058-d169470f-667d-4d5a-9d16-299978e04a3f.gif)

**Comment by Dzierzan** [comment]
It's technically implemented. But the turret should also move up and down when the actor is turning.

**Comment by michal-mad** [comment]
> It's technically implemented. But the turret should also move up and down when the actor is turning.

I am on it.
