### ISSUE TITLE
Tweak selection box bounds of units

### ISSUE THREAD

**Issue by michaeldgg2** [OpenE2140/OpenE2140#98]
@Dzierzan

**Comment by michaeldgg2** [comment]
Selection box size is in the EXE spreadsheet (Units table, Selection Box Width/Height) and the value represents rectangle like this (that is centered over the unit):

![selection box](https://cdn.discordapp.com/attachments/1080450424726884414/1088561615030468788/image.png)

**Comment by Dzierzan** [comment]
It should be closed as all current units should have correct bounds. Plus the spreadsheet has values for ORA now so every new implemented unit will have correct bounds.
